inf = input('Digite algo para ser analisado: ')
print('O tipo primitivo desse valor é {}'.format(type(inf)))
print('Só tem espaços? {}'.format(inf.isspace()))
print('É um número? {}'.format(inf.isnumeric()))
print('É alfabético? {}'.format(inf.isalpha()))
print('É alfanumérico? {}'.format(inf.isalnum()))
print('Está em maiúscula? {}'.format(inf.isupper()))
print('Está em minúscula? {}'.format(inf.islower()))
print('Está capitalizada? {}'.format(inf.istitle()))