name = input('Digite o seu nome: ')
print('Olá', name, 'seja bem-vindo')
print('---')
day = input('Qual o dia do seu nascimento? ')
month = input('Qual é o mês de seu nascimento? ')
year = input('Qual é o ano do seu nasciemnto? ')
print('Certo! Então a data do seu nascimento é ',day,"/",month,"/",year)
print('---')
print('Agora vamos fazer a soma entre dois números.')
num1 = int(input('Informe um número: '))
num2 = int(input('Agora me informe outro número: '))
result = (num1+num2)
print('A soma dos números informados é de: ',result)